--
-- 复位序列
--
ALTER SEQUENCE FXP.SEQ_NXFT_SUBJECT_ID                   RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_NXFT_ORDER_ID                     RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_NXFT_DELIVE_NOTE_ID               RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_NXFT_MEAL_ID                      RESTART WITH 100;

ALTER SEQUENCE FXP.SEQ_FAMILY_CODE                       RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_PERSON_CODE                       RESTART WITH 100;

