--
-- 行政区域表
--
-- v1.0 2014.12.08
-- author：wing
--
-- 修改历史：
--
--
-- Drop Table fxp.p_regionalism;
create Table  fxp.p_regionalism (
-- +-----------------------------+--------------+-----------+
   fregion_id                    varchar2(32)   not null,   -- 行政区域ID
   fregion_code                  varchar2(20)   not null,   -- 行政区域代码
   fregion_gbcode                varchar2(30),              -- 行政区域国标代码
   fregion_name                  varchar2(40)   not null,   -- 行政区域名称
   fat_class                     varchar2(1)    not null,   -- 区域类型 1 省 2 市 3 区 4 乡镇(街道）  5 居委会
   fat_province_id               varchar2(30),              -- 所在省ID(->行政区域ID)
   fat_city_id                   varchar2(30),              -- 所在市ID(->行政区域ID)
   fat_district_id               varchar2(30),              -- 所在区县ID(->行政区域ID)
   fat_street_id                 varchar2(30),              -- 所在乡镇ID(->行政区域ID)
   fat_committee_id              varchar2(30),              -- 所在居委会ID(->行政区域ID)
   fisavailable                  char(1)        not null,   -- 是否可用?
   fordernum                     number(6,2)    not null,   -- 排序号(本类型记录的排序号)
   fregion_desc                  varchar2(256),             -- 描述
   --
   -- 日志
   --
   fversion                      number(6)                  -- 版本号
                                 default 0      not null,
   flogcby                       varchar2(32)   not null,   -- 创建者
   flogcdate                     date default sysdate not null,   -- 创建时间
   flogluby                      varchar2(32)   not null,   -- 最后修改者
   flogludate                    date default sysdate not null,   -- 最后修改时间
   floglaby                      varchar2(32)   not null,   -- 最后访问者
   flogladate                    date default sysdate not null,   -- 最后访问时间
   --
   -- 主键、唯一键
   --
   constraint pk_p_regionalism primary key (fregion_Id),
   --
   -- 约束
   --
   constraint ck_p_regionalism_at_class   check (fat_class in ('1','2','3','4','5'))
   );

--
-- 同义词
--

--
-- 外部键约束
--
--
-- 授权
--
grant all on  fxp.p_regionalism to sf,hbcs ;
-- 精选数据
--

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('1022', '120000', '120000', '天津市', '1', '1022', '', '', '', '', 'Y', 3.00, '', 1, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('1043', '130000', '130000', '河北省', '1', '1043', '', '', '', '', 'Y', 3.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('1001', '110000', '110000', '北京市', '1', '1001', '', '', '', '', 'Y', 5.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('99999', '99999', '99999', '未知地区', '1', '99999', '', '', '', '', 'Y', 9999.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('1798', '310000', '310000', '上海市', '1', '1798', '', '', '', '', 'Y', 7.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('1927', '330000', '330000', '浙江省', '1', '1927', '', '', '', '', 'Y', 8.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('1230', '140000', '140000', '山西省', '1', '1230', '', '', '', '', 'Y', 9.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('1648', '230000', '230000', '黑龙江省', '1', '1648', '', '', '', '', 'Y', 6.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('1469', '210000', '210000', '辽宁省', '1', '1469', '', '', '', '', 'Y', 10.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2152', '350000', '350000', '福建省', '1', '2152', '', '', '', '', 'Y', 12.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2250', '360000', '360000', '江西省', '1', '2250', '', '', '', '', 'Y', 14.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2372', '370000', '370000', '山东省', '1', '2372', '', '', '', '', 'Y', 15.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2040', '340000', '340000', '安徽省', '1', '2040', '', '', '', '', 'Y', 13.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2512', '410000', '410000', '河南省', '1', '2512', '', '', '', '', 'Y', 11.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('161', '440101013', '440101013', '南村', '4', '2950', '2951', '2961', '161', '', 'Y', 1013.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('220', '440101007', '440101007', '沙傍', '4', '2950', '2951', '2961', '220', '', 'Y', 1007.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('261', '440101009', '440101009', '化龙', '4', '2950', '2951', '2961', '261', '', 'Y', 1009.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6902', '440101003049', '440101003049', '东方花园', '5', '2950', '2951', '2961', '361', '6902', 'Y', 3049.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6680', '440101003043', '440101003043', '富华路', '5', '2950', '2951', '2961', '361', '6680', 'Y', 3043.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6741', '440101003045', '440101003045', '禺山西路', '5', '2950', '2951', '2961', '361', '6741', 'Y', 3045.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6580', '440101003040', '440101003040', '西丽居委', '5', '2950', '2951', '2961', '361', '6580', 'Y', 3040.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6901', '440101003049', '440101003049', '东方花园', '5', '2950', '2951', '2961', '361', '6901', 'Y', 3049.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6863', '440101003047', '440101003047', '桥宫园', '5', '2950', '2951', '2961', '361', '6863', 'Y', 3047.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6862', '440101003048', '440101003048', '大西路', '5', '2950', '2951', '2961', '361', '6862', 'Y', 3048.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6861', '440101003046', '440101003046', '北丽园', '5', '2950', '2951', '2961', '361', '6861', 'Y', 3046.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6214', '44011300731', '44011300731', '西城花园居委', '5', '2950', '2951', '2961', '361', '6214', 'Y', 2034.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6740', '440101003044', '440101003044', '裕福花园', '5', '2950', '2951', '2961', '361', '6740', 'Y', 3044.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6640', '440101003042', '440101003042', '繁华路', '5', '2950', '2951', '2961', '361', '6640', 'Y', 3042.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6620', '440101003041', '440101003041', '工业路', '5', '2950', '2951', '2961', '361', '6620', 'Y', 3041.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6320', '440101003039', '440101003039', '汀沙村', '5', '2950', '2951', '2961', '361', '6320', 'Y', 3039.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6240', '440101002030', '440101002030', '北区', '5', '2950', '2951', '2961', '361', '6240', 'Y', 2030.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6217', '44011300735', '44011300735', '西郊村', '5', '2950', '2951', '2961', '361', '6217', 'Y', 2037.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6216', '44011300752', '44011300752', '晒布居委', '5', '2950', '2951', '2961', '361', '6216', 'Y', 2036.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6215', '44011300734', '44011300734', '禺山居委', '5', '2950', '2951', '2961', '361', '6215', 'Y', 2035.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6213', '44011300733', '44011300733', '华侨城居委', '5', '2950', '2951', '2961', '361', '6213', 'Y', 2033.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6212', '44011300751', '44011300751', '三堂居委', '5', '2950', '2951', '2961', '361', '6212', 'Y', 2032.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6211', '44011300732', '44011300732', '西涌居委', '5', '2950', '2951', '2961', '361', '6211', 'Y', 2031.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6209', '440101002029', '440101002029', '康乐居委', '5', '2950', '2951', '2961', '361', '6209', 'Y', 2029.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6208', '44011300715', '44011300715', '禺秀居委', '5', '2950', '2951', '2961', '361', '6208', 'Y', 2028.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6207', '44011300714', '44011300714', '怡乐居委', '5', '2950', '2951', '2961', '361', '6207', 'Y', 2027.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6205', '44011300711', '44011300711', '万丰居委', '5', '2950', '2951', '2961', '361', '6205', 'Y', 2025.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6204', '44011300762', '44011300762', '大市居委', '5', '2950', '2951', '2961', '361', '6204', 'Y', 2024.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6203', '44011300761', '44011300761', '瑞和园居委', '5', '2950', '2951', '2961', '361', '6203', 'Y', 2023.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6201', '44011300716', '44011300716', '桥东居委', '5', '2950', '2951', '2961', '361', '6201', 'Y', 2021.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6200', '44011300712', '44011300712', '田心居委', '5', '2950', '2951', '2961', '361', '6200', 'Y', 2020.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6199', '44011300717', '44011300717', '先锋居委', '5', '2950', '2951', '2961', '361', '6199', 'Y', 2019.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6197', '44011300708', '44011300708', '沙墟二', '5', '2950', '2951', '2961', '361', '6197', 'Y', 2017.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6196', '44011300707', '44011300707', '沙墟一', '5', '2950', '2951', '2961', '361', '6196', 'Y', 2016.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6195', '44011300709', '44011300709', '黄编村', '5', '2950', '2951', '2961', '361', '6195', 'Y', 2015.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6193', '44011300742', '44011300742', '东丽居委', '5', '2950', '2951', '2961', '361', '6193', 'Y', 2013.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6192', '44011300703', '44011300703', '社学居委', '5', '2950', '2951', '2961', '361', '6192', 'Y', 2012.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6191', '44011300702', '44011300702', '沙园居委', '5', '2950', '2951', '2961', '361', '6191', 'Y', 2011.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6206', '44011300713', '44011300713', '侨联居委', '5', '2950', '2951', '2961', '361', '6206', 'Y', 2026.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6189', '44011300706', '44011300706', '德兴居委', '5', '2950', '2951', '2961', '361', '6189', 'Y', 2009.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6720', '440113020', '440113020', '大岗', '4', '2950', '2951', '2961', '6720', '', 'Y', 3020.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2962', '440114', '440114', '花都区', '3', '2950', '2951', '2962', '', '', 'Y', 114.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2963', '440183', '440183', '增城市', '3', '2950', '2951', '2963', '', '', 'Y', 183.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2964', '440184', '440184', '从化市', '3', '2950', '2951', '2964', '', '', 'Y', 184.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2965', '440200', '440200', '韶关市', '2', '2950', '2965', '', '', '', 'Y', 200.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2950', '440000', '440000', '广东省', '1', '2950', '', '', '', '', 'Y', 1.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2800', '430000', '430000', '湖南省', '1', '2800', '', '', '', '', 'Y', 16.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2951', '440100', '440100', '广州市', '2', '2950', '2951', '', '', '', 'Y', 100.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2952', '440101', '440101', '市辖区', '3', '2950', '2951', '2952', '', '', 'Y', 101.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2953', '440102', '440102', '东山区', '3', '2950', '2951', '2953', '', '', 'Y', 102.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2954', '440103', '440103', '荔湾区', '3', '2950', '2951', '2954', '', '', 'Y', 103.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2955', '440104', '440104', '越秀区', '3', '2950', '2951', '2955', '', '', 'Y', 104.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2956', '440105', '440105', '海珠区', '3', '2950', '2951', '2956', '', '', 'Y', 105.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2957', '440106', '440106', '天河区', '3', '2950', '2951', '2957', '', '', 'Y', 106.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2958', '440107', '440107', '芳村区', '3', '2950', '2951', '2958', '', '', 'Y', 107.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2959', '440111', '440111', '白云区', '3', '2950', '2951', '2959', '', '', 'Y', 111.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2960', '440112', '440112', '黄埔区', '3', '2950', '2951', '2960', '', '', 'Y', 112.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2961', '440113', '440113', '番禺区', '3', '2950', '2951', '2961', '', '', 'Y', 100.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6', '440101005', '440101005', '石碁', '4', '2950', '2951', '2961', '6', '', 'Y', 1005.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('102', '440101006', '440101006', '东涌', '4', '2950', '2951', '2961', '102', '', 'Y', 1006.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('140', '440101001', '440101001', '沙头', '4', '2950', '2951', '2961', '140', '', 'Y', 1000.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('143', '440101019', '440101019', '石楼', '4', '2950', '2951', '2961', '143', '', 'Y', 1019.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3028', '441400', '441400', '梅州市', '2', '2950', '3028', '', '', '', 'Y', 1400.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6188', '440101002038', '440101002038', '东沙居委', '5', '2950', '2951', '2961', '361', '6188', 'Y', 2038.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6180', '44011300727', '44011300727', '丹山村', '5', '2950', '2951', '2961', '361', '6180', 'Y', 2006.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6202', '44011300763', '44011300763', '石街居委', '5', '2950', '2951', '2961', '361', '6202', 'Y', 2022.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6145', '44011300723', '44011300723', '丹桂居委', '5', '2950', '2951', '2961', '361', '6145', 'Y', 2004.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6194', '44011300705', '44011300705', '德安居委', '5', '2950', '2951', '2961', '361', '6194', 'Y', 2014.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6144', '44011300721', '44011300721', '康乐居委', '5', '2950', '2951', '2961', '361', '6144', 'Y', 2003.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6143', '44011300725', '44011300725', '侨基居委', '5', '2950', '2951', '2961', '361', '6143', 'Y', 2002.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6142', '44011300724', '44011300724', '富都居委', '5', '2950', '2951', '2961', '361', '6142', 'Y', 2001.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6181', '44011300726', '44011300726', '云星村', '5', '2950', '2951', '2961', '361', '6181', 'Y', 2007.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6210', '44011300718', '44011300718', '北郊村', '5', '2950', '2951', '2961', '361', '6210', 'Y', 2018.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6190', '440101002010', '440101002010', '桥富居委', '5', '2950', '2951', '2961', '361', '6190', 'Y', 2010.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6198', '44011300741', '44011300741', '东郊村', '5', '2950', '2951', '2961', '361', '6198', 'Y', 2008.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('361', '440113007', '440113007', '市桥街', '4', '2950', '2951', '2961', '361', '', 'Y', 1003.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6146', '44011300722', '44011300722', '康裕居委', '5', '2950', '2951', '2961', '361', '6146', 'Y', 2005.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('400', '440101010', '440101010', '新造', '4', '2950', '2951', '2961', '400', '', 'Y', 1010.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('402', '440101008', '440101008', '沙湾', '4', '2950', '2951', '2961', '402', '', 'Y', 1008.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('481', '440101011', '440101011', '大石镇', '4', '2950', '2951', '2961', '481', '', 'Y', 1011.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('482', '440101012', '440101012', '榄核镇', '4', '2950', '2951', '2961', '482', '', 'Y', 1012.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('483', '440101014', '440101014', '化龙镇', '4', '2950', '2951', '2961', '483', '', 'Y', 1014.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('486', '440101016', '440101016', '万顷沙', '4', '2950', '2951', '2961', '486', '', 'Y', 1016.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('520', '440101017', '440101017', '黄阁镇', '4', '2950', '2951', '2961', '520', '', 'Y', 1017.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('542', '440101018', '440101018', '钟村镇', '4', '2950', '2951', '2961', '542', '', 'Y', 1018.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('581', '440101019', '440101019', '鱼窝头', '4', '2950', '2951', '2961', '581', '581', 'Y', 1019.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6121', '440113002', '440113009', '东环街', '4', '2950', '2951', '2961', '6121', '', 'Y', 1000.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6122', '440113004', '440113004', '桥南街', '4', '2950', '2951', '2961', '6122', '', 'Y', 3004.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2974', '440300', '440300', '深圳市', '2', '2950', '2974', '', '', '', 'Y', 300.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2980', '440400', '440400', '珠海市', '2', '2950', '2980', '', '', '', 'Y', 400.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2990', '440600', '440600', '佛山市', '2', '2950', '2990', '', '', '', 'Y', 600.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2995', '440700', '440700', '江门市', '2', '2950', '2995', '', '', '', 'Y', 700.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3002', '440800', '440800', '湛江市', '2', '2950', '3002', '', '', '', 'Y', 800.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3011', '440900', '440900', '茂名市', '2', '2950', '3011', '', '', '', 'Y', 900.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3023', '441300', '441300', '惠州市', '2', '2950', '3023', '', '', '', 'Y', 1300.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('2695', '420000', '420000', '湖北省', '1', '2695', '', '', '', '', 'Y', 18.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3036', '441500', '441500', '汕尾市', '2', '2950', '3036', '', '', '', 'Y', 1500.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3040', '441600', '441600', '河源市', '2', '2950', '3040', '', '', '', 'Y', 1600.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3046', '441700', '441700', '阳江市', '2', '2950', '3046', '', '', '', 'Y', 1700.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3050', '441800', '441800', '清远市', '2', '2950', '3050', '', '', '', 'Y', 1800.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3060', '441900', '441900', '东莞市', '2', '2950', '3060', '', '', '', 'Y', 1900.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3061', '442000', '442000', '中山市', '2', '2950', '3061', '', '', '', 'Y', 2000.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3062', '445100', '445100', '潮州市', '2', '2950', '3062', '', '', '', 'Y', 5100.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3067', '445200', '445200', '揭阳市', '2', '2950', '3067', '', '', '', 'Y', 5200.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3074', '445300', '445300', '云浮市', '2', '2950', '3074', '', '', '', 'Y', 5300.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4389', '440500', '440500', '汕头市', '2', '2950', '4389', '', '', '', 'Y', 500.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4400', '441200', '441200', '肇庆市', '2', '2950', '4400', '', '', '', 'Y', 1200.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3081', '450000', '450000', '广西壮族自治区', '1', '3081', '', '', '', '', 'Y', 26.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3574', '530000', '530000', '云南省', '1', '3574', '', '', '', '', 'Y', 24.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3219', '460000', '460000', '海南省', '1', '3219', '', '', '', '', 'Y', 19.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3248', '500000', '500000', '重庆市', '1', '3248', '', '', '', '', 'Y', 20.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3282', '510000', '510000', '四川省', '1', '3282', '', '', '', '', 'Y', 21.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4003', '630000', '630000', '青海省', '1', '4003', '', '', '', '', 'Y', 22.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3792', '610000', '610000', '陕西省', '1', '3792', '', '', '', '', 'Y', 23.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3710', '540000', '540000', '西藏自治区', '1', '3710', '', '', '', '', 'Y', 25.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3896', '620000', '620000', '甘肃省', '1', '3896', '', '', '', '', 'Y', 29.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4056', '640000', '640000', '宁夏回族自治区', '1', '4056', '', '', '', '', 'Y', 30.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4088', '650000', '650000', '新疆维吾尔自治区', '1', '4088', '', '', '', '', 'Y', 31.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4259', '320000', '320000', '江苏省', '1', '4259', '', '', '', '', 'Y', 28.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('3483', '520000', '520000', '贵州省', '1', '3483', '', '', '', '', 'Y', 27.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6970', '440113012', '440113012', '南村镇', '4', '2950', '2951', '2961', '6970', '6970', 'Y', 9001.00, '', 0, 'ADMIN', sysdate, 'ADMIN', sysdate, 'ADMIN', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6950', '440113119', '440113119', '钟村镇', '4', '2950', '2951', '2961', '6950', '', 'Y', 6950.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('487', '440113013', '440113013', '洛浦街', '4', '2950', '2951', '2961', '487', '', 'Y', 1011.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6219', '44011300701', '44011300701', '桥福居委', '5', '2950', '2951', '2961', '361', '6219', 'Y', 1.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('8010', '440113105', '440113105', '石楼镇', '4', '2950', '2951', '2961', '8010', '', 'Y', 4001.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('8110', '440113116', '440113116', '榄核镇', '4', '2950', '2951', '2961', '8110', '', 'Y', 4001.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('8150', '440113118', '440113118', '沙湾镇', '4', '2950', '2951', '2961', '8150', '', 'Y', 4001.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6218', '44011300704', '44011300704', '东兴居委', '5', '2950', '2951', '2961', '361', '6218', 'Y', 2020.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4523', '810000', '810000', '香港特别行政区', '1', '4523', '', '', '', '', 'Y', 32.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4184', '710000', '710000', '台湾省', '1', '4184', '', '', '', '', 'Y', 33.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4185', '820000', '820000', '澳门特别行政区', '1', '4185', '', '', '', '', 'Y', 34.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('4244', '220000', '220000', '吉林省', '1', '4244', '', '', '', '', 'Y', 35.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6910', '440113120', '440113120', '石碁镇', '4', '2950', '2951', '2961', '6910', '6910', 'Y', 9000.00, '', 0, 'ADMIN', sysdate, 'ADMIN', sysdate, 'ADMIN', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6909', '440113902', '440113902', '大龙街', '4', '2950', '2951', '2961', '6909', '6909', 'Y', 9000.00, '', 0, 'ADMIN', sysdate, 'ADMIN', sysdate, 'ADMIN', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('6990', '440113103', '440113103', '新造镇', '4', '2950', '2951', '2961', '6990', '6990', 'Y', 4001.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

insert into p_regionalism (FREGION_ID, FREGION_CODE, FREGION_GBCODE, FREGION_NAME, FAT_CLASS, FAT_PROVINCE_ID, FAT_CITY_ID, FAT_DISTRICT_ID, FAT_STREET_ID, FAT_COMMITTEE_ID, FISAVAILABLE, FORDERNUM, FREGION_DESC, FVERSION, FLOGCBY, FLOGCDATE, FLOGLUBY, FLOGLUDATE, FLOGLABY, FLOGLADATE)
values ('8040', '440113107', '440113107', '东涌镇', '4', '2950', '2951', '2961', '8040', '', 'Y', 4001.00, '', 0, 'admin', sysdate, 'admin', sysdate, 'admin', sysdate);

commit;
