--
-- 复位序列
--
ALTER SEQUENCE FXP.SEQ_FAMILY_CODE                 RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_PERSON_CODE                 RESTART WITH 100;

ALTER SEQUENCE FXP.SEQ_ORG_DIGITAL_NUMBER           RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_QYH_USER_ID                  RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_COUPON_NO                    RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_CHGNOTE_NO                   RESTART WITH 100;

ALTER SEQUENCE FXP.SEQ_BOSS_ID                      RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_CIRCLE_ID                    RESTART WITH 100;
ALTER SEQUENCE FXP.SEQ_TEAM_ID                      RESTART WITH 100;

ALTER SEQUENCE FXP.SEQ_ORDER_ID                     RESTART WITH 100;
